config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  get 'users/:id/posts' => 'users#submissions', as: :user_submissions
  get 'users/:id/comments' => 'users#comments', as: :user_comments

  get 'posts/newest' => 'posts#newest', as: :newest_posts

  resources :posts do
    resources :comments
  end

  get 'comments/newest' => 'comments#newest', as: :newest_comments

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :voter, class_name: 'User'

  validates_uniqueness_of :user_id, scope => [:comment_id]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :post_votes

  validates :title, presence: true
  validate :body_or_url


  private
  def body_or_url
    if !(body.blank? ^ url.blank?)
      flash[:errors] = "You must enter a url or post text."
    end
  end
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :post
  belongs_to :voter, class_name: 'User'

  validates_uniqueness_of :user_id, scope => [:post_id]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments, foreign_key: :commenter_id

  validates :username, uniqueness: true
  validates :username, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :find_current_user, :logged_in?

  def logged_in?
    @logged_in = !!session[:user_id]
  end

  def require_login
    unless logged_in?
      flash[:errors] = "You must be logged in to submit."
      redirect_to login_path
    end
  end

  def find_current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:new,:create, :edit, :destroy]
  def index
    @post = Post.find_by(params[:id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.new(comment_params)
    comment.commenter = @current_user
    post = Post.find_by(id: params[:post_id])
    comment.post = post
    if comment.save
      redirect_to post_path(post)
    else
      flash[:errors] = comment.errors.full_messages
      redirect_to post_path(post)
    end
  end

  def newest
   @comments = Comment.all.order("created_at desc")
  end

  def show

  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :upvotes)
  end

end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new,:edit,:destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user = @current_user
    if post.save
      redirect_to post_path(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def newest
    @posts = Post.all.order("created_at desc")
    render :'posts/newest'
  end


  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    post = Post.find_by(id: params[:id])
    post.update_attributes(post_params)
    votes = PostVote.where(post_id: post.id, voted: true).count
    post.update_attributes(upvotes: votes)
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :body, :upvotes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to user_path(@current_user)
    end
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user
      if user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:errors] = "Invalid username and password combination."
        redirect_to login_path
      end
    else
      flash[:errors] = "Username does not exist."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if session[:user_id]
      redirect_to user_path(@current_user)
    else
      @user = User.new
      redirect_to login_path
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @user_posts = @user.posts
  end

  def submissions
    @submissions = User.find_by(id: params[:id]).posts
  end

  def comments
    @comments = User.find_by(id: params[:id]).comments
  end

  def edit
    #edit password
  end

  def update
    #update attributes :password and :karma
  end

  def destroy
    #delete account and log out
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :karma)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_votes_helper.rb
module PostVotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/postvotes_helper.rb
module PostvotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.erb
<br>
<% @comments.each do |comment| %>
 <div class="comments">
  <small> by <%= link_to comment.commenter.username, user_path(comment.commenter) %> on <%=comment.created_at%></small>
  <br><%= comment.body %>
  </div>
<% end %>

app/views/comments/newest.erb
<br>
<% @comments.each do |comment| %>
 <div class="comments">
  <small> by <%= link_to comment.commenter.username, user_path(comment.commenter) %> on <%=comment.created_at%></small>
  <br><%= comment.body %>
  </div>

<% end %>

app/views/comments/show.erb
<%= form_for [@post, @comment] do |f| %>
  <%=f.text_area :body, :cols => 70, :rows => 7%><br>
  <%=f.submit "add comment"%>
<%end%>

<% @post.comments.each do |comment| %>
 <div class="comments">
  <small> by <%= link_to comment.commenter.username, user_path(comment.commenter) %> on <%=comment.created_at%></small>
  <br><%= comment.body %>
  </div>
<% end %>

app/views/posts/edit.erb
<%= form_for @post do |f| %>
  <%= f.label 'title:(required)' %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label 'url    :' %><br>
  <%= f.text_field :url %><br><br>
  <strong> or </strong><br><br>
  <%= f.label 'text :' %><br>
  <%=f.text_area :body, :cols => 70, :rows => 12%><br><br>
  <%=f.submit %>
<%end%>

app/views/posts/index.erb
<ol>
  <% @posts.each do |post| %>
    <li><%= link_to "∆", edit_post_path(post), class: "vote" %> <%= link_to post.title, post_path(post) %><br><small><%=post.upvotes%> points by <%= post.user.username %> | <%= link_to "#{post.comments.count} comments", post_comments_path(post_id: post.id) %> </small></li>
  <% end %>
</ol>

app/views/posts/new.erb
<% if flash[:errors] %>
  <br><div class="errors">
    <%= flash[:errors].to_s %>
  </div><br>
<% end %>

<h3>Submit</h3>

<%= form_for @post do |f| %>
  <%= f.label 'title:(required)' %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label 'url    :' %><br>
  <%= f.text_field :url %><br><br>
  <strong> or </strong><br><br>
  <%= f.label 'text :' %><br>
  <%=f.text_area :body, :cols => 70, :rows => 12%><br><br>
  <%=f.submit "submit"%>
<%end%>

<p>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.</p>

app/views/posts/newest.erb
<ol>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %><br><small><%=post.upvotes%> points by <%= post.user.username %> | <%= link_to "#{post.comments.count} comments", post_comments_path(post_id: post.id) %> </small></li>
  <% end %>
</ol>

app/views/posts/show.erb
<br>
<%= @post.title %>
<br>
<small><%=@post.upvotes%> points by <%= @post.user.username %> | <%= @post.comments.count %> comments </small>
</br>
<p> <%= @post.body%> </p>
<br>

<%= form_for [@post, @comment] do |f| %>
  <%=f.text_area :body, :cols => 70, :rows => 7%><br>
  <%=f.submit "add comment"%>
<%end%>

<% @post.comments.each do |comment| %>
 <div class="comments">
  <small> by <%= link_to comment.commenter.username, user_path(comment.commenter) %> on <%=comment.created_at%></small>
  <br><%= comment.body %>
  </div>
<% end %>

app/views/users/comments.erb
<br>
<% @comments.each do |comment| %>
  <div>
  <%= link_to comment.post.title, post_path(comment.post) %><br>
  <small> on <%=comment.created_at%> (<%= comment.upvotes %> )</small><br>
  <%= comment.body %>
  </div>

<% end %>

app/views/users/show.erb
<table>
  <tr>
    <td class="left">user:</td>
    <td class="right"><%= @user.username %></td>
  </tr>
  <tr>
    <td class="left">created:</td>
    <td class="right"><%= @user.created_at %></td>
  </tr>
  <tr>
    <td class="left">karma:</td>
    <td class="right"><%= @user.karma %></td>
  </tr>
  <tr>
    <td class="left"></td>
    <td class="right"><%= link_to "change password", edit_user_path(@user) %></td>
  </tr>
  <tr>
    <td class="left"></td>
    <td class="right"><%= link_to "submissions", user_submissions_path(@user) %></td>
  </tr>
  <tr>
    <td class="left"></td>
    <td class="right"><%= link_to "comments", user_comments_path(@user) %></td>
  </tr>
</table>

app/views/users/submissions.erb
<br>
<% @submissions.each do |sub| %>
  <li><%= link_to sub.title, post_path(sub) %><br><small>submitted <%=sub.created_at%></small></li>
<% end %>